### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Teals53** [imayushsaini/Bombsquad-Ballistica-Modded-Server#39]
Valid server config file loaded.
Launching server subprocess...
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/teals53/Bombsquad-Ballistica-Modded-Server/nbstreamreader.py", line 25, in _populateQueue
    self._target(*self._args, **self._kwargs)
  File "/home/teals53/Bombsquad-Ballistica-Modded-Server/nbstreamreader.py", line 25, in _populateQueue
    raise UnexpectedEndOfStream
nbstreamreader.UnexpectedEndOfStream
    raise UnexpectedEndOfStream
nbstreamreader.UnexpectedEndOfStream
FATAL ERROR: Unhandled exception in game thread:
Traceback (most recent call last):
Server subprocess exited with code 1.
Stopping subprocess...
Subprocess stopped.

**Comment by Teals53** [comment]
Teals53#1508

i tried most thing can u help me to setup ?

**Comment by imayushsaini** [comment]
Can you shares logs file , 
also pull latest changes .

**Comment by Teals53** [comment]
tbh i need a manual help can u contact me via discord ?

**Comment by Teals53** [comment]
i really want to use it can u give me more detailed explanation ? for setup from strach or pls contact me tysm

**Comment by Teals53** [comment]
i made it

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/167312699-8d0f910a-3f72-4f4e-8d6e-9f63f24e82ce.png)
what i need to fix that ? and no one can able to connect my server it says some error

**Comment by Teals53** [comment]
its soo weird fr

**Comment by PUFFY-41XD** [comment]
> 

I think use those and tell. Me if it works step by step
1.sudo apt install software-properties-common -y
2.sudo add-apt-repository ppa:deadsnakes/ppa -y
3.sudo apt update
4.sudo apt install python3.9-dev -y
