### ISSUE TITLE
Error loop

### ISSUE THREAD

**Issue by Hiradpi** [imayushsaini/Bombsquad-Ballistica-Modded-Server#78]
KeyboardInterrupt
>>> Bootstraping mods...
ERROR: Error in plugin on_app_running()
  root call: <unavailable>
  context: <UI Context>
  real-time: 777
  sim-time: <unavailable>
  base-time: <unavailable>
PRINTED-FROM:
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_meta.py", line 223, in _handle_scan_results
    self._scan_complete_cb()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 510, in on_meta_scan_complete
    self._update_state()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 538, in _update_state
    self.on_app_running()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 491, in on_app_running
    self.plugins.on_app_running()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_plugin.py", line 93, in on_app_running
    _error.print_exception('Error in plugin on_app_running()')
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_error.py", line 168, in print_exception
    stackstr = ''.join(traceback.format_stack())
EXCEPTION:
  Traceback (most recent call last):
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_plugin.py", line 89, in on_app_running
      plugin.on_app_running()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/custom_hooks.py", line 55, in on_app_running
      bootstraping()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/custom_hooks.py", line 108, in bootstraping
      pdata.load_cache()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/playersData/pdata.py", line 713, in load_cache
      get_profiles()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/playersData/pdata.py", line 89, in get_profiles
      profiles = json.load(f)
    File "/usr/lib/python3.10/json/__init__.py", line 293, in load
      return loads(fp.read(),
    File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Hiradpi** [comment]
and I saw on your fix logs it seams that you did not fix it it's my first time running bs server please fix it 


`root@debian:~/bombserver/Bombsquad-Ballistica-Modded-Server# python3.10 bombsquad_server 
Bcs server manager 1.3 starting up (debug mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.                                      
Valid server config file loaded.
>>> Launching server subprocess...
BCS Build 1.7.19
Get help on https://discord.gg/ucyaesh
Get Updates from - https://github.com/imayushsaini/Bombsquad-Ballistica-Modded-Server
Watch tutorials  https://youtube.com/c/HeySmoothy
BCS Headless  1.7.20 build 21005.
FATAL ERROR: Unable to bind to requested udp port 43210 (ipv4)
STACK-TRACE-BEGIN:
./bombsquad_headless(+0x1f378d) [0x5574bb20278d]
./bombsquad_headless(+0x11efba) [0x5574bb12dfba]
./bombsquad_headless(+0x11ccc2) [0x5574bb12bcc2]
./bombsquad_headless(+0x1eacf5) [0x5574bb1f9cf5]
./bombsquad_headless(+0x1eb084) [0x5574bb1fa084]
./bombsquad_headless(+0x1ee00f) [0x5574bb1fd00f]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc473) [0x7f9d32774473]
/lib/x86_64-linux-gnu/libc.so.6(+0x883ec) [0x7f9d324433ec]
/lib/x86_64-linux-gnu/libc.so.6(+0x108a1c) [0x7f9d324c3a1c]
STACK-TRACE-END
Bootstraping mods...
ERROR: Error in plugin on_app_running()
  root call: <unavailable>
  context: <UI Context>
  real-time: 784
  sim-time: <unavailable>
  base-time: <unavailable>
PRINTED-FROM:
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_meta.py", line 223, in _handle_scan_results
    self._scan_complete_cb()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 510, in on_meta_scan_complete
    self._update_state()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 538, in _update_state
    self.on_app_running()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_app.py", line 491, in on_app_running
    self.plugins.on_app_running()
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_plugin.py", line 93, in on_app_running
    _error.print_exception('Error in plugin on_app_running()')
  File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_error.py", line 168, in print_exception
    stackstr = ''.join(traceback.format_stack())
EXCEPTION:
  Traceback (most recent call last):
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_data/python/ba/_plugin.py", line 89, in on_app_running
      plugin.on_app_running()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/custom_hooks.py", line 55, in on_app_running
      bootstraping()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/custom_hooks.py", line 108, in bootstraping
      pdata.load_cache()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/playersData/pdata.py", line 713, in load_cache
      get_profiles()
    File "/root/bombserver/Bombsquad-Ballistica-Modded-Server/dist/ba_root/mods/playersData/pdata.py", line 89, in get_profiles
      profiles = json.load(f)
    File "/usr/lib/python3.10/json/__init__.py", line 293, in load
      return loads(fp.read(),
    File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
      raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Server subprocess exited with code 1.
Stopping subprocess...
Subprocess stopped.
`

**Comment by imayushsaini** [comment]
> FATAL ERROR: Unable to bind to requested udp port 43210 (ipv4)

Seems like other process running on this port 43210 , close that task or use different port.

> get_profiles
profiles = json.load(f)
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Here error is in your profiles.json file, looks like your profiles.json file is empty for some reason, make sure file downloaded currectly or saved (in case you manually edited it).

**Comment by Hiradpi** [comment]
no I did not change it but TNX for your help tho if its posible please consider working on your scripts error handling 
If skids like me were able to understand those long ass python3 errors we would have been programmers by now lol :)

**Comment by Hiradpi** [comment]
and please consider adding examples too for each config it would help a lot for beginners like me

**Comment by Hiradpi** [comment]
I have noticed that config.json keeps getting updated whenever I stop or restart the server i cannot change the group names from barfi and lado to something i weant

**Comment by imayushsaini** [comment]
> I have noticed that config.json keeps getting updated whenever I stop or restart the server i cannot change the group names from barfi and lado to something i weant

Team names are changed from config.yaml , mentioned in readme. You are modifying wrong file.
